// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv5mtjgd7Qn6Cy9U6V_un7L15WyWHtL6c',
    appId: '1:60756091071:web:707043bd444cf3bfb6260a',
    messagingSenderId: '60756091071',
    projectId: 'crumb-club',
    authDomain: 'crumb-club.firebaseapp.com',
    storageBucket: 'crumb-club.firebasestorage.app',
    measurementId: 'G-MZTEL9EWYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlMXY_WrwWAHePFIjBrwzbsIvFPL-jUOY',
    appId: '1:60756091071:android:32692b6ce5cbaca4b6260a',
    messagingSenderId: '60756091071',
    projectId: 'crumb-club',
    storageBucket: 'crumb-club.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA68BU_BLpXfGQK4pqjRP6va3-7w85K5H4',
    appId: '1:60756091071:ios:68f2087b3d3c666fb6260a',
    messagingSenderId: '60756091071',
    projectId: 'crumb-club',
    storageBucket: 'crumb-club.firebasestorage.app',
    iosBundleId: 'com.example.crumbClub',
  );
}
